name = "Boopii Client"
author = "Jack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "507bae141ab269fdd48ba33589d7ff7bd3f6b8efc90d371d43558e8e743aac1c"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
