name = "Boopii Client"
author = "Jack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49ed9053c3c009d92c244cefbab9510db19a36ee4ac01db4f5576c1baa337c4b"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
